//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class exceltutorsEntities : DbContext
    {
        public exceltutorsEntities()
            : base("name=exceltutorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Contents> Contents { get; set; }
        public virtual DbSet<OptionA> OptionA { get; set; }
        public virtual DbSet<OptionB> OptionB { get; set; }
        public virtual DbSet<OptionC> OptionC { get; set; }
        public virtual DbSet<OptionD> OptionD { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
    }
}
